<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/stylesheet.css">
    <title>S.S.C</title>
</head>
<body>
    <!--NAV BAR-->
    <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top" >
        <div class="container-fluid">
          <a class="navbar-brand" href="S.S.C.html">
            <img src="assets/images/LogoMakr-6lUwrs.png">&trade;
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="S.S.C.html">HOME</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="About.html"> ABOUT</a>
              </li>

            <li class="nav-item">
                <a class="nav-link" href="Music.html">MUSIC</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="Events.html">EVENTS</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="ContactUs.html">CONTACT US</a>
            </li>



              <li class="nav-item dropdown">
                
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-shop">SHOP</i>
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="clothing.html">clothing</a></li>
                  <li><a class="dropdown-item" href="Shop.html">BEATS</a></li>
                  <li><a class="dropdown-item" href="Shop.html">Graphic design</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="book.html">Book artist or studio</a></li>
                </ul>
              </li>
              
             
              

            </ul>

            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>

            <li class="nav-item">
                <a href="cart.html"><i class="fa-solid fa-cart-shopping"></i></a>
                <a href="account.html"><i class="fa-solid fa-person-walking"></i></a>
            </li>

          </div>
        </div>
      
      </nav>
      <!--NAVBAR END-->

      
   

      <!--Home-->
    <Section id="home ">
       
      
            <div class="footer">
             
                <button class="left" onclick="plusDivs(-1)">&#10094;</button>  
                    <div class="ImageSlide">
                        
                        <a href="html/Shop.html">
                            <img src="assets/images/rm.jpeg" alt="" class="Slide">

                            <img src="assets/images/Mask.jpg" alt="" class="Slide">

                            <img src="assets/images/MIRROR.jpg" alt="" class="Slide">
                        </a>
                    </div>
                
                
                <button class="right" onclick="plusDivs(+1)">&#10095;</button>
            </div>
        
    </Section>
    
        <div class="promotion">
            $WEET$AVAGE CREATIONS
        </div>  
            <div class="Slogan">

                <h1>A Form Of Polarity </h1> 
                <p>SWEETSAVAGE is more of a lifestyle than a clothing brand,<br>  theaching people that there Are two sides in every situation in life. <br> Most people tend to look at life one sided and miss opportunities in the other side. </p>
                    <div class="button">
                        <button>    <a href="About.html">Learn more</a></button>
                    </div>

            </div>
 
            <!--fEATURED PRODUCTS-->
        <section id="FeaturedProducts"  class="w-100">
                
                <H1 class="text-center">Featured Products</H1>
        
            <div class="products">

                <div class="row mx-0 container-fluid">
                    <div class="product text-center col-lg-3 col-md-6 col-sm-12 ">
                        <div class="img-fluid ">
                            <img   src="assets/images/products/balance/unisex-heavy-blend-hoodie-indigo-blue-front-623c8f7310fb6.png" alt="Balance">
                            <div class="star">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                            </div>
                        <h5 class="p-name">Balance Hoodie</h5>
                        <h4 class="p-price">R500</h4>
                        <button class="buy-button" ><a href="balance.html">Buy now</a></button>
                        </div>
                    </div>
                    <div class="product text-center  col-lg-3 col-md-6 col-sm-12">
                        <div class="img-fluid ">
                            <img  src="assets/images/products/attract/mens-long-sleeve-shirt-black-front-623c8ea284e95.png" alt="attract">
                            <div class="star">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                            </div>
                            <h5 class="p-name">Attract Sweater</h5>
                        <h4 class="p-price">R500</h4>
                        <button class="buy-button" ><a href="single_product.html">Buy now</a></button>
                        </div>
                    </div>
                    <div class="product text-center col-lg-3 col-md-6 col-sm-12 ">
                        <div class="img-fluid ">
                            <img src="assets/IMAGES/products/standard/unisex-staple-t-shirt-white-front-622f98dbe175d.png" alt="Standard">
                            <div class="star">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                            </div>
                            <h5 class="p-name">Standard T-shirt</h5>
                        <h4 class="p-price">R500</h4>
                        <button class="buy-button" ><a href="single_product.html">Buy now</a></button>
                        </div>
                    </div>
                    <div class="product text-center col-lg-3 col-md-6 col-sm-12">
                        <div class="img-fluid ">
                            <img  src="assets/images/products/caps/5-panel-trucker-cap-black-white-black-front-622f9865d921f.jpg" alt="Atract">
                            <div class="star">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                            </div>
                            <h5 class="p-name">Trucker Cap</h5>
                        <h4 class="p-price">R500</h4>
                        <button class="buy-button" ><a href="caps.html">Buy now</a></button>
                        </div>
                    </div>
                    
                    
                   
                </div>

            </div>
        </section>

        <h1 class="text-center">XO_PRINSAVAGE</h1>
        <h2 class="text-center">Founder Of S.S.C</h2>
            <!--Music-->
            <section id="new" class="row p-0 m-0">
                
                <div class="one col-lg-3 col-md-6 col-sm-12">
                    <img  src="assets/images/331AA592-E6D0-4B42-9F93-15AB40EEEFF5.png" alt=""> 
                    <div class="details">
                         <h3>RESPECT &copy;</h3><br>
                        <p>"Put Some Respect On My Name" 
                            <br> <BR>
                            Released : June 2020 <br>
                            ARTISTS : XO_PRINSAVAGE <br>
                            PRODUCER : VADOR <br>
                            COVER ART : SWEETSAVAGE CREATIONS <br>
                            MIXER : MGM THE GRAND</p> 
                    
                    </div>
                    <button class="text-uppercase" href="">Listen</button>
                </div>

                <div class="one col-lg-3 col-md-6 col-sm-12">
                    <img src="assets/images/9B960D5B-D1B8-423D-8BF1-C07CB88DB432.png" alt=""> 
                    <div class="details">
                        <h3>STAR-GAZING &copy;</h3><br>
                        <p>“MAMA KNOW SHE RAISED A STAR SHE
                            WILL CELEBRATE” <br> 
                            This is a song about focus, dedicaion and manifistation of the life you want to live. <br>
                            Released on: 2021-01-01
                            ARTISTS : XO_PRINSAVAGE & INTEGRATE <br>
                            PRODUCER : MGM THE GRAND <br>
                            COVER ART : SWEETSAVAGE CREATIONS <br></p> 
                    
                    </div>
                    <button  class="text-uppercase" href="">Listen</button>
                </div>

                <div class="one col-lg-3 col-md-6 col-sm-12">
                    <img src="assets/images/1E4A9C4D-A88F-4223-92AA-FB457F0195A0.png" alt=""> 
                   
                    <div class="details">
                         <h3>MOONLIGHT&copy;</h3> <br>
                        <p> "TUNNEL VISSION MY ONLY THOUDGTS IS REACHING MY DESTINATION" <br> <br>
                            Released on: 2021-08-13 <br>
                            ARTISTS : XO_PRINSAVAGE <br>
                            PRODUCER : VADOR <br>
                            COVER ART : SWEETSAVAGE CREATIONS <br>
                            MIXER : SIPHO NDINISA</p> 
                    
                    </div>
                    <button class="text-uppercase" href="">Listen</button>
                </div>
                
                <div class="one col-lg-3 col-md-6 col-sm-12">
                    <img src="assets/images/3805bd6a-20d6-4dc4-97d2-7ec623860cf1.400x400.jpg" alt=""> 
                    <div class="details">
                        <br> <h3>F.Y.N &copy;</h3>
                        <p>“ {SWIM}x3 ,GO FIND YOUR NEMO” <br> <br>
                            The History of Valentine’s Day <br> 
                            Released on: 2022-02-25 <br>
                            ARTISTS : XO_PRINSAVAGE <br>
                            PRODUCER : ZIYANDA BEATS <br>
                            COVER ART : SWEETSAVAGE CREATIONS <br>
                            MIXER : SIPHO NDINISA</p> 
                   
                    </div>
                    <button class="text-uppercase" href="">Listen</button>
                </div>
            </section>
    
            <div class="BottomFooter ">
                <div class="logo-2 col-lg-4 col-md-6 col-sm-12">
                    <a href=""><img src="assets/images/LogoMakr-6ULcz6.png" alt="logo"></a> 
                </div>
               
                <div class="links-2 col-lg-4 col-md-6 col-sm-12">
                    
                    <ul class="nav flex-column">
                      <h3 class="txt "> Links</h3>
                      <li class="nav-item">
                            <a  class="nav-link2" href="html/S.S.C.html">HOME</a>
                        </li>
          
                        <li class="nav-item">
                            <a class="nav-link2" href="html/Shop.html">SHOP</a>
                        </li>
          
                        <li class="nav-item">
                            <a class="nav-link2" href="html/Music.html">MUSIC</a>
                        </li class="nav-item">
          
                        <li class="nav-item">
                            <a class="nav-link2" href="html/Events.html">EVENTS</a>
                        </li>
          
                        <li class="nav-item">
                            <a class="nav-link2" href="html/Contact Us.html">CONTACT US</a>
                        </li>
          
                    </ul>
                </div>
                <div class="social-media col-lg-4 col-md-6 col-sm-12">
          
                    <h3 class="txt"> Social Media</h3>
                    <li>
                        <i class="fa-brands fa-youtube  " > <a href="https://www.youtube.com/channel/UCnNQ1MQlnxTDeTXWOMkcRvQ">Youtube</a> </i> 
                    </li>
                    <li>
                        <i class="fa-brands fa-instagram"> <a href="https://www.instagram.com/sweetsavage.creations/">Instagram</a></i>
                    </li>
                    <li>
                        <i class="fa-brands fa-facebook"> <a href="https://web.facebook.com/SweetSavageCreation/">Facebook</a></i>
                    </li>
                    <li>
                        <i class="fa-brands fa-x-twitter"><a href="https://www.youtube.com/channel/UCnNQ1MQlnxTDeTXWOMkcRvQ"> X</a></i>
                    </li>
                    <li>
                        <i class="fa-brands fa-whatsapp"> <a href="https://www.youtube.com/channel/UCnNQ1MQlnxTDeTXWOMkcRvQ"> WhatsApp</a></i>
                    </li>
          
          
                </div>
              
          
            </div>

        </div>
    </div>
    <script>
        var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("Slide");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  x[slideIndex-1].style.display = "block";  
}
    </script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/430cdb8140.js" crossorigin="anonymous"></script>
</body>
</html>